export const PageElements = {
  battleLog: `.inner.message-log`,
  currentTurn: `//h2[text()="Turn #"]`,
  megaEvolve: `input[name="megaevo"]`,
  moveControls: `.movecontrols`,
  pokemonHealth: `.whatdo .healthy`,
  undoButton: `button[name="undoChoice"]`,
  waitingForOpponent: `//em[text()="Waiting for opponent..."]`,
  instantReplay: `button[name="instantReplay"]`,
  chatInput: `.battle-log-add .chatbox textarea`,
  skipTurn: `button[name="goToEnd"]`,
  saveReplay: `button[name="saveReplay"]`,
  replayLink: `.replay-link`,
  closeBattle: `.closebutton`,
};
